version: '3'

services:
  app:
    build: .
    volumes:
      - nfs_volume:/data
    environment:
      - LDAP_SERVER=ldap://ldap_server:389
      - LDAP_BASE_DN=dc=example,dc=com
    networks:
      - ldap_network

  ldap_server:
    image: osixia/openldap:latest
    environment:
      - LDAP_ORGANISATION=Example Inc.
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin_password
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d
    networks:
      - ldap_network

networks:
  ldap_network:

volumes:
  nfs_volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/nfs_share"